### ISSUE TITLE
优量汇 激励视频加载失败 ，报错如下，跪求大佬帮助

### ISSUE THREAD

**Issue by CoCoXXXX** [CocosService/tradplusDemo#5]
E/gdt_ad_mob: 此构造方法即将废弃，请在 Application 中初始化 SDK 后，使用不带 appId 的构造方法，详细请参考Demo

021-07-22 17:39:24.365 21862-21969/xyz.tinigame.infinity E/gdt_ad_mob: Exception while init Reward Video AD Core
    com.qq.e.comm.managers.plugin.c: Fail to getfactory implement instance for interface:com.qq.e.comm.pi.POFactory
        at com.qq.e.comm.managers.plugin.PM.a()
        at com.qq.e.comm.managers.plugin.PM.b()
        at com.qq.e.ads.rewardvideo.RewardVideoAD$1.run()
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.NoSuchMethodError: No static method getInstance()Lcom/qq/e/comm/managers/GDTADManager; in class Lcom/qq/e/comm/managers/GDTADManager; or its super classes (declaration of 'com.qq.e.comm.managers.GDTADManager' appears in /data/app/xyz.tinigame.infinity-1/base.apk)
        at com.qq.e.comm.plugin.util.ak.a(A:31)
        at com.qq.e.comm.plugin.a.<init>(A:79)
        at com.qq.e.comm.plugin.POFactoryImpl.<init>(A:8)
        at com.qq.e.comm.plugin.POFactoryImpl.<clinit>(A:10)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.qq.e.comm.managers.plugin.PM.a() 
        at com.qq.e.comm.managers.plugin.PM.b() 
        at com.qq.e.ads.rewardvideo.RewardVideoAD$1.run() 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761)

**Comment by CloseToZero** [comment]
优量汇SDK的版本好像是比较旧的版本，你有没有在项目中自己集成了优量汇SDK，导致用了旧的版本？如果有的话，尝试去掉，然后再试试。

**Comment by CoCoXXXX** [comment]
感谢回复，我是使用的demo在cocos中开通服务进行打包测试的，appId，和广告位ID是使用的自己在tradplus后台创建的数据来测试的。设备是在安卓模拟器上。使用得是demo中的优量汇SDK，会报错。我又替换了最新版本的优量汇SDK，还是会报错

**Comment by CloseToZero** [comment]
我想问题在于编译时填写的包名和TradPlus后台创建的Android应用包名不匹配，你可以去TradPlus后台查看下包名，后台应用管理那里，在你创建的Android应用名旁边，有个编辑按钮，点下就可以看到包名了。
如果你中途有更新优量汇SDK，记得还原回去。
